### PR TITLE
Implement pmaxub

### LINKED ISSUE #872: apt update in Ubuntu i386 rootfs crashes because of illegal instruction
If I boot in Ubuntu i386 rootfs and try to run “apt update”, I get illegal instruction error, here is the dmesg log:
`[    0.000000] 10 illegal instruction at 0xf7aa674d: 0f de d8 66 0f de e2 66`

### PR DESCRIPTION
**Pull request by akemimadoka**
This may fix #872

### CODE REVIEW

**Comment by gzz2000** [comment]
I can confirm that this works. Thank you!

**Comment by tbodt** [comment]
Somehow I entirely missed this PR! Looks pretty good, just want to enable a test for the instruction.

**Comment by tbodt** [comment]
Thanks for the contribution, and sorry for the delay :)

**Comment by qwerzl** [comment]
still `Illegal instruction`…
125FB169-7135-4718-BF70-73D2A3824795

This is the latest version from TestFlight.

**Comment by tbodt** [comment]
This PR hasn't made it to TestFlight yet. Check again in about an hour.

**Comment by qwerzl** [comment]
Alright. Thanks.

**Pull request merged**
