### PR TITLE
Add cpuinfo and filesystems to /proc, enhance /proc/meminfo, Amber appearance.  

### PR DESCRIPTION
**Pull request by emkey1**
Third attempt.

### CODE REVIEW

**Comment by nimelehin** [comment]
Hey! My recommendation for you is to try to stash all commits into the first one. Google `git rebase` for more information

**Comment by emkey1** [comment]
> Hey! My recommendation for you is to try to squash all commits into the first one. Google `git rebase` for more information

Thank you for the tip.  I'll look into this.  I'm assuming the merge would be cleaner with that fix?  

Right now I'm trying to get my fork into a sane state which should make things like this easier.  I'm almost tempted to blow the whole thing away and start over.

**Comment by saagarjha** [comment]
Will take a more detailed look later, but it would be nice if you could pull unrelated changes out of this PR (specifically, the theme-related ones). And for those: we have theming planned, so stay tuned for those to land first.

**Comment by emkey1** [comment]
> Will take a more detailed look later, but it would be nice if you could pull unrelated changes out of this PR (specifically, the theme-related ones). And for those: we have theming planned, so stay tuned for those to land first.

That should be the only unrelated change.  

In theory, your request should be easy.  Heck, it's only two lines.  In practice I'll probably have a concussion by the time I convince git to do what I want again.  :)

If I had this to do over again I'd have done three seperate commits and merges.  One for each of the /proc changes/additions basically.

**Comment by emkey1** [comment]
Closing this one, new request submitted.

**Pull request closed without merging**
