### PR TITLE
Support a New Theming System

### PR DESCRIPTION
**Pull request by 0x41c**
## Backstory (tl;dr, I'm this guy : https://github.com/ish-app/ish/pull/526)
Two years ago I was trying to get into software development as a hobby and had no place to start. I loved how technical iOS development was (Or really any type of development for that matter) and I wanted to find a place to start. But at that time I lacked the skills needed to accomplish a UI system rewrite for iSH (I could barely make a simple point system in obj-c). I instead spent my time modifying storyboard files and sending screenshots of them. It was either that or copy and paste already written code.

For that I would like to apologize. I wanted to accomplish something, and might have rubbed a few people in the wrong way while doing so. 

To say it plain and simple (this is cringe),  I'm back to finish what I started. 

Btw tbodt, thanks for the support you showed me back then (Even if I was an untrained wannabe).
I can say years later that your kindness opened me up to the best community I could ever be in.

#### Now lets get onto the actual changes and proposals

So the aim in this PR is to rewrite the theming system to add user-defined theming capabilities. It is also possible that in the near future, exporting and importing themes will be implemented in this PR because of how everything is stored in NSUserDefaults (Can be converted to a JSON file and back for import/export). However, the following criteria should be met before I would be comfortable with seeing it in the application:

- [x] Ability to preform R/W Operations on all themes
- [x] Palette Customization
- [x] Rewritten theme selector with per-theme previews
- [x] Import/Export of themes

These are the non-essential but quality additions

- [ ] File system unique appearance preferences
- [ ] Open multitasking pages with separate theme
- [ ] Cursor customization ( Block/line/underscore/Color?)

Endgame:
- [ ] Full terminal profile functionality (Like in iTerm2)

### CODE REVIEW

**Comment by saagarjha** [comment]
> To say it plain and simple (this is cringe), I'm back to finish what I started.

On the contrary, it is based! We're glad to see you back and interested in contributing to iSH. That being said, I've been working on the theming code myself (though not much as of late), so it's possible that we might choose that implementation over yours. You're free to continue working on your version (and we might choose to merge it or steal ideas from it if it turns out to be good) but I just wanted to give you a heads-up on where themes are today.

**Comment by 62f** [comment]
The cursor is always black, which makes it difficult to spot it over a dark background.

image

__Originally posted by @lifepillar in https://github.com/ish-app/ish/issues/1377__

**Comment by c0dine** [comment]
I have a system that I am going to set up which should allow you to set a custom pallet for all the colours shown in the terminal. That should include the terminal cursor (Custom cursors 👀). To clarify what I plan to accomplish I'll update this PR's description and include some other ideas that I want to add to the bonus features. 

**To the developers:** Yes I know right now it doesn't look like I have started a rewrite so-to-speak but I am just slowly transitioning into changes since this effects almost all of the app UI. To accommodate this transition, I'll have multiple branches targeting certain features on my fork after I complete the requirements for this system.

**Review by Tattooedbarbie — APPROVED** [review]

**Comment by 0x41c** [comment]
Closing this in light of @saagarjha's PR https://github.com/ish-app/ish/pull/1740

**Pull request closed without merging**
