### PR TITLE
Add sys_membarrier

### PR DESCRIPTION
**Pull request by jason-conway**
Handles `MEMBARRIER_CMD_QUERY` and throws everything else at a thread fence... low risk, low reward.

Also stubs sys_getcpu() to allow stress-ng to run

### CODE REVIEW

**Comment by me355** [comment]
Shah

**Comment by me355** [comment]
Noneo8

**Comment by saagarjha** [comment]
membarrier is intended to be a memory barrier across all threads of the process, not just the task that called it. I haven't looked at what Linux is doing here but I suspect it involves using signals to support correctly on macOS, or parking the thread.

**Comment by jason-conway** [comment]
may revisit this in the future, but closing this out for now

**Pull request closed without merging**
