### PR TITLE
Terminate mount after dismissing a document picker

### LINKED ISSUE #703: Terminate mount command automatically after cancelling the document picker
When I tap or click the outside of the document picker, it will be closed with the `mount` command still running. So, I have to press Ctrl+C to terminate it.

Please see the following video.

https://youtu.be/MTSSxKa6qgk

Is it possible to terminate the `mount` command automatically after cancelling the document picker?

### PR DESCRIPTION
**Pull request by kkk669**
Fixes #703

### CODE REVIEW

**Comment by tbodt** [comment]
Thanks for finding this!

Could you make sure it works on iOS 12? The API you're using says it was added in iOS 13.

**Comment by kkk669** [comment]
@tbodt I completely forgot to test in iOS 12. I will check that tomorrow.

**Comment by kkk669** [comment]
@tbodt I tested on the iOS 12.4 simulator and the 11.4 one and both of them worked well. `UIAdaptivePresentationControllerDelegate` itself has been added since iOS 8, so my modifications can be compiled for iOS 12. Besides, iOS 12.4 or earlier cannot dismiss a modal sheet like iOS 13, so it doesn't need `presentationControllerDidDismiss`.

**Comment by tbodt** [comment]
Looks good. Thanks!

**Pull request merged**
