### PR TITLE
Add Solarized

### PR DESCRIPTION
**Pull request by Mnpn03**
This adds the Solarized Light and Dark foreground and background colours as themes in `About > Appearance`. It's not the full Solarized palette, only a regular iSH theme.

<details>
  <summary>Show images</summary>

sol1

sol2
</details>

From recent comment by @apas on issue #14.

### CODE REVIEW

**Comment by apas** [comment]
@Mnpn03, this is amazing. Truly fast PR! I hope @tbodt will approve and merge.

**Comment by tbodt** [comment]
Not sure if I should merge this since this is only the foreground and background colors, not the full theme. Also we need a real theming system, that dictionary there is getting a little out of control.

**Comment by apas** [comment]
> since this is only the foreground and background colors

Aren't the other iSH themes the same?

**Comment by tbodt** [comment]
The other iSH themes don't want a custom palette. Solarized kinda needs it.

**Comment by apas** [comment]
Right. Personally I'd be content with just fore/background Light/Dark. (The interesting thing is Solarized's test works just because you report `$TERM` as `xterm-256color`.)

Solarized

**Comment by apas** [comment]
Hello; kindly bumping this. Is there a final decision? I think there are users who will enjoy a Solarized addition, even if it's not the full theme and just fore/background colors.

**Comment by tbodt** [comment]
My decision right now is to not add more theme presets until there's a better theming interface in place.

**Pull request closed without merging**
