### PR TITLE
Speedup proc_print_escaped()

### PR DESCRIPTION
**Pull request by jason-conway**
Also check that `str` is nonnull before dereference

### CODE REVIEW

**Review by saagarjha — APPROVED** [review]
LGTM, aside from the nit that we don't really need a null check here. The caller should do that validation themselves

**Comment by jason-conway** [comment]
Figured f286240 wasn't worth a separate PR; lmk if I should revert it

**Review by saagarjha — CHANGES_REQUESTED** [review]
These code paths are not really performance-critical, so we'd like the balance for this code to lean towards readability and maintainability rather than maximum speed. In this case it would be appropriate to rely on whatever the optimizing compiler is willing to emit unless there's a good reason otherwise.

**Review by saagarjha — APPROVED** [review]

**Comment by tbodt** [comment]
Please rebase on master to fix CI

**Pull request merged**
