### PR TITLE
CPU refactor+ptrace

### PR DESCRIPTION
**Pull request by saagarjha**
Still in progress, but would appreciate feedback.

### CODE REVIEW

**Comment by saagarjha** [comment]
Progress: `PTRACE_TRACEME`+`PTRACE_SINGLESTEP` seem to work in the small test I have. I can get about 50,000 single steps/second on my iPad.

**Comment by saagarjha** [comment]
Just checking for merge conflicts.

**Comment by hazcod** [comment]
ping @saagarjha

**Comment by saagarjha** [comment]
I started working on something else and I'll need to fix the merge conflicts before I can get back to this. Hopefully someday…

**Comment by saagarjha** [comment]
Flew too close to the sun

**Pull request closed without merging**
